Repository orbs-network/orbs-network, pull requests merged in 2018-03, with the labels that each got.

#82 Feature/delivery to clients
  .circleci/config.yml
  Dockerfile
  deploy/README.md
  deploy/bootstrap/.env
  deploy/bootstrap/bootstrap.sh
  deploy/bootstrap/crontab
  deploy/bootstrap/docker-compose.yml
  deploy/cloudformation/README.md
  deploy/cloudformation/basic-infrastructure.yaml
  deploy/cloudformation/create-stacks.js
  deploy/cloudformation/create-stacks.parity.sh
  deploy/cloudformation/create-stacks.sh
  deploy/cloudformation/node.yaml
  deploy/cloudformation/parameters.basic-infrastracture.json
  deploy/cloudformation/parameters.json
  deploy/cloudformation/parameters.node.json
  deploy/cloudformation/parameters.parity.json
  deploy/cloudformation/test.parity.sh
  deploy/cloudformation/test.sh
  deploy/deploy-staging.sh
  deploy/package.json
  deploy/parity/bootstrap.sh
  deploy/src/deploy.js
  deploy/test/parity-test.js
  docker-test.sh
  e2e/test-from-docker.sh
  projects/libs/core-library-typescript/src/consensus/block-builder.ts
  projects/libs/core-library-typescript/src/consensus/raft-consensus.ts
  projects/libs/core-library-typescript/src/gossip/gossip.ts
  projects/services/consensus-service-typescript/src/index.ts
  projects/services/gossip-service-typescript/src/index.ts
  projects/services/gossip-service-typescript/src/service.ts
  projects/services/public-api-service-typescript/src/index.ts
  projects/services/sidechain-connector-service-typescript/src/index.ts
  projects/services/storage-service-typescript/src/index.ts
  projects/services/virtual-machine-service-typescript/src/index.ts
Labels: rfc

#86 Initial Crypto SDK (utilities)
  .circleci/config.yml
  client/README.md
  client/crypto-sdk/.clang-format
  client/crypto-sdk/.gitignore
  client/crypto-sdk/CMakeLists.txt
  client/crypto-sdk/Dockerfile
  client/crypto-sdk/build.sh
  client/crypto-sdk/clean.sh
  client/crypto-sdk/configure.sh
  client/crypto-sdk/docker-build.sh
  client/crypto-sdk/gtest.cmake
  client/crypto-sdk/lib/CMakeLists.txt
  client/crypto-sdk/lib/account.cpp
  client/crypto-sdk/lib/account.h
  client/crypto-sdk/lib/base58.cpp
  client/crypto-sdk/lib/base58.h
  client/crypto-sdk/lib/crc32.cpp
  client/crypto-sdk/lib/crc32.h
  client/crypto-sdk/lib/crypto.cpp
  client/crypto-sdk/lib/crypto.h
  client/crypto-sdk/lib/ripemd160.cpp
  client/crypto-sdk/lib/ripemd160.h
  client/crypto-sdk/lib/sha256.cpp
  client/crypto-sdk/lib/sha256.h
  client/crypto-sdk/lib/sha512.cpp
  client/crypto-sdk/lib/sha512.h
  client/crypto-sdk/lib/utils.cpp
  client/crypto-sdk/lib/utils.h
  client/crypto-sdk/libgcrypt.cmake
  client/crypto-sdk/libgpg-error.cmake
  client/crypto-sdk/test.sh
  client/crypto-sdk/test/CMakeLists.txt
  client/crypto-sdk/test/account-test.cpp
  client/crypto-sdk/test/base58-test.cpp
  client/crypto-sdk/test/crc32-test.cpp
  client/crypto-sdk/test/main.cpp
  client/crypto-sdk/test/ripemd160-test.cpp
  client/crypto-sdk/test/sha256-test.cpp
  client/crypto-sdk/test/sha512-test.cpp
  client/crypto-sdk/test/utils-test.cpp
Labels: client

#94 e2e pre-existing config support fix + code dependency improvements
  e2e/package.json
  e2e/src/orbs-client.ts
  e2e/src/public-api-client.ts
  e2e/src/test-config.ts
  e2e/yarn.lock
Labels: bug

#95 Run e2e on testnet
  .circleci/config.yml
  .circleci/deploy.sh
  .circleci/docker-pull.sh
  .circleci/e2e-testnet.sh
  docker-build.sh
  docker-tag.sh
  docker-test.sh
Labels: circle ci, enhancement

#90 Run tests in FIPS140-2 mode as well
  .circleci/config.yml
  client/crypto-sdk/lib/crypto.cpp
  client/crypto-sdk/lib/crypto.h
  client/crypto-sdk/test/CMakeLists.txt
  client/crypto-sdk/test/main.cpp
  client/crypto-sdk/test/sha256-test.cpp
Labels: client

#100 Enable Subscription Manager on Staging
  deploy/bootstrap/docker-compose.yml
  deploy/parity/docker-compose.yml
  e2e/src/test-environment/ethereum-simulation-node.ts
  projects/libs/core-library-typescript/src/public-api/transaction-handler.ts
Labels: testnet

#97 e2e stress test
  e2e/README.md
  e2e/package.json
  e2e/src/stress-test.ts
  e2e/src/test-config.ts
  e2e/test-from-docker.sh
  e2e/test-from-host.sh
Labels: enhancement, testnet

#102 Sidechain connector settings
  deploy/bootstrap/bootstrap.sh
  deploy/bootstrap/docker-compose.yml
  deploy/cloudformation/node.yaml
  deploy/parity/docker-compose.yml
  projects/services/virtual-machine-service-typescript/src/index.ts
Labels: bug, testnet

#99 Clear transaction pool
  projects/architecture/interfaces/virtual-machine.proto
  projects/libs/core-library-typescript/src/block-storage/block-storage-sync.ts
  projects/libs/core-library-typescript/src/block-storage/block-storage.ts
  projects/libs/core-library-typescript/src/common-library/topologyPeers.ts
  projects/libs/core-library-typescript/src/consensus/block-builder.ts
  projects/libs/core-library-typescript/src/consensus/raft-consensus.ts
  projects/libs/core-library-typescript/src/index.ts
  projects/libs/core-library-typescript/src/test-kit/fake-gossip-client.ts
  projects/libs/core-library-typescript/src/test-kit/index.ts
  projects/libs/core-library-typescript/src/test-kit/service-ipc-client.ts
  projects/libs/core-library-typescript/src/transaction-pool/transaction-pool.ts
  projects/libs/core-library-typescript/src/virtual-machine/virtual-machine.ts
  projects/libs/core-library-typescript/test/block-storage/block-storage-sync.spec.ts
  projects/libs/core-library-typescript/test/block-storage/block-storage.spec.ts
  projects/libs/core-library-typescript/test/consensus/block-builder.spec.ts
  projects/libs/core-library-typescript/test/transaction-pool/transaction-pool.spec.ts
  projects/libs/core-library-typescript/test/virtual-machine/virtual-machine.spec.ts
  projects/services/consensus-service-typescript/src/transaction-pool-service.ts
  projects/services/storage-service-typescript/src/block-storage-service.ts
  projects/services/storage-service-typescript/test/node-loader.ts
Labels: bug

#98 CryptoSDK node.js C++ addon (using the latest N-API)
  .circleci/config.yml
  .circleci/setup-rngd.sh
  Dockerfile
  build.sh
  build/src/build-ts.js
  build/src/watch-ts.js
  client/crypto-sdk-javascript/.clang-format
  client/crypto-sdk-javascript/.gitignore
  client/crypto-sdk-javascript/LICENSE
  client/crypto-sdk-javascript/binding.gyp
  client/crypto-sdk-javascript/build.sh
  client/crypto-sdk-javascript/package.json
  client/crypto-sdk-javascript/src/address.cpp
  client/crypto-sdk-javascript/src/address.h
  client/crypto-sdk-javascript/src/crypto-sdk.cpp
  client/crypto-sdk-javascript/src/index.ts
  client/crypto-sdk-javascript/test.sh
  client/crypto-sdk-javascript/test/address.spec.ts
  client/crypto-sdk-javascript/tsconfig.json
  client/crypto-sdk-javascript/tsconfig.test.json
  client/crypto-sdk-javascript/tslint.json
  client/crypto-sdk-javascript/yarn.lock
  client/crypto-sdk/CMakeLists.txt
  client/crypto-sdk/Dockerfile
  client/crypto-sdk/README.md
  client/crypto-sdk/build.sh
  client/crypto-sdk/configure.sh
  client/crypto-sdk/docker-build.sh
  client/crypto-sdk/lib/address.cpp
  client/crypto-sdk/lib/address.h
  client/crypto-sdk/lib/base58.cpp
  client/crypto-sdk/lib/utils.cpp
  client/crypto-sdk/lib/utils.h
  client/crypto-sdk/libgcrypt.cmake
  client/crypto-sdk/libgpg-error.cmake
  client/crypto-sdk/rebuild.sh
  client/crypto-sdk/test/address-test.cpp
  client/crypto-sdk/test/base58-test.cpp
  client/crypto-sdk/test/sha512-test.cpp
  client/crypto-sdk/test/utils-test.cpp
  config/projects.json
  docker/bootstrap-sdk.sh
  docker/bootstrap-server.sh
  e2e/package.json
  e2e/src/chai-bars-plugin.ts
  e2e/src/simple-smart-contracts.spec.ts
  e2e/test-from-docker.sh
  e2e/yarn.lock
Labels: client

#106 Speed up crypto-sdk build: Run 3rd party library tests only on CI
  Dockerfile
  client/crypto-sdk/CMakeLists.txt
  client/crypto-sdk/libgcrypt.cmake
  client/crypto-sdk/libgpg-error.cmake
  docker-build.sh
  e2e/test-from-docker.sh
Labels: client

#105 Misc refactoring: Logger initialization, repo logo, rename of errorHandler
  logo.jpg
  projects/libs/core-library-typescript/src/base-service/service.ts
  projects/libs/core-library-typescript/src/common-library/error-handler.ts
  projects/libs/core-library-typescript/src/common-library/index.ts
  projects/libs/core-library-typescript/test/subscription-manager/stub-erc-subscription-validation._spec.ts
  projects/services/consensus-service-typescript/src/index.ts
  projects/services/gossip-service-typescript/src/index.ts
  projects/services/public-api-service-typescript/src/index.ts
  projects/services/sidechain-connector-service-typescript/src/index.ts
  projects/services/storage-service-typescript/src/index.ts
  projects/services/virtual-machine-service-typescript/src/index.ts
Labels: enhancement
